---
- hosts: "{{host}}"
  user: "root"
  gather_facts: no
  tasks:
   - name: Yum install php depend package
     yum: name={{ item }} state=present
     with_items:
       - pcre
       - pcre-devel
       - gcc
       - gcc-c++
       - autoconf
       - libjpeg
       - libjpeg-devel
       - libpng 
       - libpng-devel 
       - freetype 
       - freetype-devel 
       - libxml2 
       - libxml2-devel 
       - zlib 
       - zlib-devel 
       - glibc 
       - glibc-devel 
       - glib2 
       - glib2-devel 
       - bzip2 
       - bzip2-devel 
       - ncurses 
       - ncurses-devel 
       - curl 
       - curl-devel 
       - libidn 
       - libidn-devel 
       - openssl 
       - openssl-devel 
       - make
   - name: create user {{ php_user }}
     user: name={{ php_user }}  shell=/sbin/nologin

   - name: copy source package to {{ host }}
     copy: src={{ ansible_php_package }}/{{ item.name }} dest=/usr/local/src/{{ item.name }} mode=755
     with_items:
       - { name: 'libiconv-1.13.1.tar.gz' }
       - { name: 'libmcrypt-2.5.8.tar.gz' }
       - { name: 'mhash-0.9.9.9.tar.gz' }
       - { name: 'mcrypt-2.6.8.tar.gz' }
       - { name: 'php-5.6.30.tar.bz2' }
       - { name: 'redis-2.2.7.tgz' }
       - { name: 'mongo-1.6.8.tgz' }
       - { name: 'memcache-2.2.7.tgz' }
       - { name: 'imagick-3.1.2.tgz' }
       - { name: 'ImageMagick-6.9.8-4.tar.gz' }

   - name: install ImageMagick-6.9.8-4
     shell: cd /usr/local/src/ && tar -xzf ImageMagick-6.9.8-4.tar.gz && cd ImageMagick-6.9.8-4  && ./configure && make && make install

   - name: install libiconv-1.13.1
     shell: cd /usr/local/src/ && tar -xzf libiconv-1.13.1.tar.gz && cd libiconv-1.13.1/ && ./configure --prefix=/usr/local && make && make install

   - name: install libmcrypt-2.5.8
     shell: cd /usr/local/src/ && tar -xzf libmcrypt-2.5.8.tar.gz && cd libmcrypt-2.5.8/ && ./configure  && make && make install && /sbin/ldconfig && cd libltdl/ && ./configure --enable-ltdl-install && make && make install

   - name: install mhash-0.9.9.9
     shell: cd /usr/local/src/ && tar -xzf mhash-0.9.9.9.tar.gz && cd mhash-0.9.9.9/ && ./configure  && make && make install

   - name: check system bit   
     shell: getconf LONG_BIT
     register: result     

   - name: make soft link
     file: src=/usr/local/lib/{{ item.name }} dest=/usr/lib64/{{ item.name }} state=link
     with_items:
       - { name: 'libmcrypt.la' }
       - { name: 'libmcrypt.so' }
       - { name: 'libmcrypt.so.4' }
       - { name: 'libmcrypt.so.4.4.8' }
       - { name: 'libmhash.a' }
       - { name: 'libmhash.la' }
       - { name: 'libmhash.so' }
       - { name: 'libmhash.so.2' }
       - { name: 'libmhash.so.2.0.1' }
       - { name: 'libmcrypt-config' }
       - { name: 'libmhash.so' }
     when: result.stdout  == 64

   - name: install mcrypt-2.6.8
     shell: cd /usr/local/src/ && tar -xzf mcrypt-2.6.8.tar.gz && cd mcrypt-2.6.8/ && /sbin/ldconfig  && ./configure  && make && make install

   - name: tar php-5.6.30
     shell: cd /usr/local/src/ && tar -jxf php-5.6.30.tar.bz2

   - name: configure php
     shell: cd /usr/local/src/php-5.6.30 && ./configure --prefix="{{php_path}}" --with-config-file-path="{{php_path}}"/etc --with-pdo-mysql=mysqlnd  --with-mysql=mysqlnd --with-mysqli=mysqlnd --with-iconv-dir=/usr/local --with-freetype-dir --with-jpeg-dir --with-png-dir --with-zlib --with-libxml-dir=/usr --enable-xml --disable-rpath --enable-bcmath --enable-shmop --enable-sysvsem --enable-inline-optimization --with-curl=/usr/local  --enable-mbregex --enable-fpm --enable-mbstring --with-mcrypt --with-gd --enable-gd-native-ttf --with-openssl --with-mhash --enable-pcntl --enable-sockets  --with-xmlrpc --enable-zip --enable-soap  --without-pear --enable-zip  --enable-calendar --enable-ftp --enable-ctype --enable-exif --disable-ipv6 --with-sqlite3 --enable-pdo --disable-phar

   - name: install php-5.6.30
     shell: cd /usr/local/src/php-5.6.30 && CPU_NUM=$(cat /proc/cpuinfo | grep processor | wc -l);if [ $CPU_NUM -gt 1 ];then make ZEND_EXTRA_LIBS='-liconv' -j$CPU_NUM ;else  make ZEND_EXTRA_LIBS='-liconv';fi && make install

   - name: copy php config file
     template: src={{ansible_php_config}}/{{ item.name }} dest={{php_path}}/etc/{{ item.name }}
     with_items:
       - { name: 'php.ini' }
       - { name: 'php-fpm.conf' }

   - name: install php ext packages
     shell: cd /usr/local/src/ && tar -xzf "{{ item.name }}".tgz && cd "{{ item.name }}" && "{{php_path}}"/bin/phpize && ./configure --with-php-config="{{php_path}}"/bin/php-config && make  && make install
     with_items:
       - { name: 'redis-2.2.7' }
       - { name: 'memcache-2.2.7' }
       - { name: 'imagick-3.1.2' }
       - { name: 'mongo-1.6.8' }

   - name: make php start scripts
     template: src={{ansible_php_config}}/php-fpm dest=/etc/init.d/php-fpm mode=755

   - name: Encure php-fpm is running
     service: name=php-fpm state=started enabled=yes  

  handlers:
    - name:  restart php-fpm
      service: name=php-fpm state=restarted
